// ── MCS CoWorker Mock Data ─────────────────────────────────────────────────────
// Realistic mocked data for all tabs in the demo

export const mockPlugins = [
  {
    id: "plugin_email_triage",
    name: "Email Triage",
    description: "Classifies incoming emails and routes them to the right plugin",
    enabled: true,
    status: "running",
    lastRun: "2 min ago",
    nextRun: "8 min",
    schedule: "Every 10 minutes",
    runsToday: 42,
    successRate: 98,
    model: "haiku",
    category: "Core",
  },
  {
    id: "plugin_auto_response_elio",
    name: "Auto Response (Elio)",
    description: "Drafts and sends automatic replies for routine client enquiries",
    enabled: true,
    status: "running",
    lastRun: "5 min ago",
    nextRun: "5 min",
    schedule: "Every 10 minutes",
    runsToday: 38,
    successRate: 95,
    model: "sonnet",
    category: "Core",
  },
  {
    id: "plugin_correspondence_logger",
    name: "Correspondence Logger",
    description: "Logs all client email correspondence to the activity database",
    enabled: true,
    status: "idle",
    lastRun: "12 min ago",
    nextRun: "3 min",
    schedule: "Every 15 minutes",
    runsToday: 28,
    successRate: 100,
    model: "haiku",
    category: "Core",
  },
  {
    id: "plugin_noa_processor",
    name: "NOA Processor",
    description: "Detects ATO Notice of Assessment emails and extracts tax data",
    enabled: true,
    status: "idle",
    lastRun: "1 hr ago",
    nextRun: "On event",
    schedule: "Event-driven",
    runsToday: 3,
    successRate: 100,
    model: "sonnet",
    category: "Tax",
  },
  {
    id: "plugin_asic_returns",
    name: "ASIC Returns",
    description: "Monitors and processes ASIC annual return reminders",
    enabled: true,
    status: "idle",
    lastRun: "3 hrs ago",
    nextRun: "Tomorrow 9am",
    schedule: "Daily 9:00am",
    runsToday: 1,
    successRate: 100,
    model: "sonnet",
    category: "Compliance",
  },
  {
    id: "plugin_morning_briefing",
    name: "Morning Briefing",
    description: "Sends a daily digest of jobs, inbox, and FuseSign status via Teams",
    enabled: true,
    status: "idle",
    lastRun: "Today 8:00am",
    nextRun: "Tomorrow 8am",
    schedule: "Daily 8:00am",
    runsToday: 1,
    successRate: 100,
    model: "sonnet",
    category: "Briefings",
  },
  {
    id: "plugin_wip_summariser",
    name: "WIP Ageing Summariser",
    description: "Scans XPM for stale jobs and drafts a partner summary",
    enabled: true,
    status: "idle",
    lastRun: "2 hrs ago",
    nextRun: "2 hrs",
    schedule: "Every 4 hours",
    runsToday: 2,
    successRate: 100,
    model: "sonnet",
    category: "Practice Mgmt",
  },
  {
    id: "plugin_debtor_followup",
    name: "Debtor Follow-Up",
    description: "Finds overdue invoices and drafts follow-up emails",
    enabled: true,
    status: "idle",
    lastRun: "Today 9:00am",
    nextRun: "Tomorrow 9am",
    schedule: "Daily 9:00am",
    runsToday: 1,
    successRate: 100,
    model: "sonnet",
    category: "Practice Mgmt",
  },
  {
    id: "plugin_meeting_prep",
    name: "Meeting Prep Brief",
    description: "Detects meeting requests and drafts client prep briefs",
    enabled: true,
    status: "idle",
    lastRun: "30 min ago",
    nextRun: "30 min",
    schedule: "Every 30 minutes",
    runsToday: 8,
    successRate: 88,
    model: "sonnet",
    category: "Practice Mgmt",
  },
  {
    id: "plugin_fusesign_monitor",
    name: "FuseSign Monitor",
    description: "Monitors pending envelopes and sends reminders for overdue docs",
    enabled: true,
    status: "idle",
    lastRun: "2 hrs ago",
    nextRun: "2 hrs",
    schedule: "Every 2 hours",
    runsToday: 4,
    successRate: 100,
    model: "haiku",
    category: "Compliance",
  },
  {
    id: "plugin_engagement_letter",
    name: "Engagement Letter Generator",
    description: "Drafts engagement letters for new clients detected in email",
    enabled: true,
    status: "idle",
    lastRun: "Yesterday",
    nextRun: "On event",
    schedule: "Event-driven",
    runsToday: 0,
    successRate: 100,
    model: "sonnet",
    category: "Onboarding",
  },
  {
    id: "plugin_bas_reminder",
    name: "BAS Reminder Drafter",
    description: "Drafts BAS reminder emails on ATO due dates",
    enabled: false,
    status: "disabled",
    lastRun: "28 Oct",
    nextRun: "28 Apr",
    schedule: "Quarterly",
    runsToday: 0,
    successRate: 100,
    model: "sonnet",
    category: "Tax",
  },
  {
    id: "plugin_annual_review",
    name: "Annual Review Prompt",
    description: "Identifies clients due for annual review and drafts outreach",
    enabled: true,
    status: "idle",
    lastRun: "1 Apr",
    nextRun: "1 May",
    schedule: "Monthly 1st",
    runsToday: 0,
    successRate: 100,
    model: "sonnet",
    category: "Client Relations",
  },
  {
    id: "plugin_client_outreach",
    name: "Client Outreach",
    description: "Sends personalised outreach emails using client history",
    enabled: true,
    status: "idle",
    lastRun: "1 hr ago",
    nextRun: "1 hr",
    schedule: "Every 2 hours",
    runsToday: 4,
    successRate: 92,
    model: "sonnet",
    category: "Client Relations",
  },
];

export const mockActivityLog = [
  { id: 1, time: "09:42", plugin: "Email Triage", action: "Classified 3 emails — 2 TAX_DOCUMENT, 1 GENERAL_ENQUIRY", status: "success" },
  { id: 2, time: "09:40", plugin: "Auto Response (Elio)", action: "Drafted reply to Sarah Chen re: FY2025 tax return timeline", status: "success" },
  { id: 3, time: "09:38", plugin: "Email Triage", action: "Classified 1 email — NOA_RECEIVED → woke NOA Processor", status: "success" },
  { id: 4, time: "09:38", plugin: "NOA Processor", action: "Extracted NOA for Marcus Webb — Taxable income $142,800, Tax payable $38,450", status: "success" },
  { id: 5, time: "09:35", plugin: "Correspondence Logger", action: "Logged 5 emails to activity database", status: "success" },
  { id: 6, time: "09:30", plugin: "Meeting Prep Brief", action: "Drafted prep brief for 10am meeting — James Thornton (Thornton Holdings)", status: "success" },
  { id: 7, time: "09:20", plugin: "WIP Ageing Summariser", action: "Found 4 jobs stalled >14 days — drafted partner summary", status: "success" },
  { id: 8, time: "09:15", plugin: "Debtor Follow-Up", action: "Identified 3 overdue invoices — drafted follow-up emails (pending approval)", status: "warning" },
  { id: 9, time: "09:00", plugin: "Morning Briefing", action: "Sent daily briefing to Teams — 12 open jobs, 3 FuseSign pending, 8 unread emails", status: "success" },
  { id: 10, time: "08:45", plugin: "Email Triage", action: "Classified 2 emails — 1 ASIC_NOTICE, 1 CLIENT_QUERY", status: "success" },
  { id: 11, time: "08:30", plugin: "FuseSign Monitor", action: "Reminder sent to David Park — engagement letter unsigned for 5 days", status: "success" },
  { id: 12, time: "08:15", plugin: "Auto Response (Elio)", action: "ERROR: Graph API rate limit — retrying in 60s", status: "error" },
  { id: 13, time: "08:00", plugin: "Morning Briefing", action: "Fetching XPM jobs...", status: "success" },
  { id: 14, time: "07:55", plugin: "ASIC Returns", action: "Processed ASIC reminder for Thornton Holdings Pty Ltd — due 30 Apr", status: "success" },
];

export const mockApprovals = [
  {
    id: "appr_001",
    plugin: "Debtor Follow-Up",
    action: "Send follow-up email to Chen Family Trust",
    detail: "Invoice #INV-2024-0892 — $4,200 — 32 days overdue",
    confidence: 0.71,
    created: "9:15am today",
    priority: "medium",
    draftPreview: "Dear Ms Chen,\n\nI hope this message finds you well. I'm writing regarding invoice #INV-2024-0892 for $4,200 dated 15 March 2025, which remains outstanding...",
  },
  {
    id: "appr_002",
    plugin: "Debtor Follow-Up",
    action: "Send follow-up email to Park & Associates",
    detail: "Invoice #INV-2024-0901 — $8,750 — 45 days overdue",
    confidence: 0.68,
    created: "9:15am today",
    priority: "high",
    draftPreview: "Dear Mr Park,\n\nThis is a follow-up regarding invoice #INV-2024-0901 for $8,750 which is now 45 days past due. We would appreciate your prompt attention...",
  },
  {
    id: "appr_003",
    plugin: "Client Outreach",
    action: "Send annual review invitation to Webb Family Trust",
    detail: "Last contact: 14 months ago — flagged for annual review",
    confidence: 0.72,
    created: "8:30am today",
    priority: "low",
    draftPreview: "Dear Mr Webb,\n\nIt has been over a year since we last reviewed your financial position. Given the changes in the current tax landscape, I'd like to schedule...",
  },
];

export const mockMemory = [
  { id: "mem_001", client: "Chen Family Trust", type: "email", summary: "Discussed FY2025 tax return — client travelling until May, prefers email contact", date: "2 days ago", relevance: 0.94 },
  { id: "mem_002", client: "Thornton Holdings", type: "noa", summary: "NOA processed — FY2024 taxable income $892,400, refund $12,300 issued", date: "1 week ago", relevance: 0.91 },
  { id: "mem_003", client: "Park & Associates", type: "outreach", summary: "Sent BAS reminder — client acknowledged, lodgement due 28 Feb", date: "3 weeks ago", relevance: 0.87 },
  { id: "mem_004", client: "Webb Family Trust", type: "email", summary: "Engagement letter signed — new client onboarding complete", date: "1 month ago", relevance: 0.83 },
  { id: "mem_005", client: "Nguyen Investments", type: "email", summary: "Query about CGT on property sale — referred to senior accountant", date: "2 months ago", relevance: 0.79 },
];

export const mockEvents = [
  { id: "evt_001", time: "09:42:15", type: "email.triage.complete", source: "plugin_email_triage", payload: "3 emails classified" },
  { id: "evt_002", time: "09:42:15", type: "plugin.run.complete", source: "plugin_loader", payload: "plugin_email_triage" },
  { id: "evt_003", time: "09:38:02", type: "email.noa.detected", source: "event_wiring", payload: "Woke NOA Processor" },
  { id: "evt_004", time: "09:38:05", type: "plugin.run.complete", source: "plugin_loader", payload: "plugin_noa_processor" },
  { id: "evt_005", time: "09:35:00", type: "heartbeat.tick", source: "heartbeat", payload: "tick #2847" },
  { id: "evt_006", time: "09:30:12", type: "plugin.run.complete", source: "plugin_loader", payload: "plugin_meeting_prep" },
  { id: "evt_007", time: "09:25:00", type: "heartbeat.tick", source: "heartbeat", payload: "tick #2846" },
  { id: "evt_008", time: "09:20:08", type: "plugin.run.complete", source: "plugin_loader", payload: "plugin_wip_summariser" },
  { id: "evt_009", time: "09:15:33", type: "approval.queued", source: "plugin_debtor_followup", payload: "2 actions queued (confidence < 0.75)" },
  { id: "evt_010", time: "09:00:00", type: "plugin.run.complete", source: "plugin_loader", payload: "plugin_morning_briefing" },
];

export const mockUsageData = {
  todayCost: 1.84,
  monthlyCost: 38.20,
  monthlyBudget: 100,
  totalCalls: 847,
  totalTokensIn: 1240000,
  totalTokensOut: 380000,
  byPlugin: [
    { name: "Auto Response (Elio)", calls: 312, cost: 14.20, model: "sonnet" },
    { name: "Email Triage", calls: 280, cost: 3.10, model: "haiku" },
    { name: "NOA Processor", calls: 45, cost: 6.80, model: "sonnet" },
    { name: "Morning Briefing", calls: 30, cost: 4.50, model: "sonnet" },
    { name: "WIP Summariser", calls: 60, cost: 4.20, model: "sonnet" },
    { name: "Meeting Prep", calls: 72, cost: 3.80, model: "sonnet" },
    { name: "Other plugins", calls: 48, cost: 1.60, model: "mixed" },
  ],
  byDay: [
    { date: "Apr 11", cost: 1.20 },
    { date: "Apr 12", cost: 1.85 },
    { date: "Apr 13", cost: 0.90 },
    { date: "Apr 14", cost: 2.10 },
    { date: "Apr 15", cost: 1.65 },
    { date: "Apr 16", cost: 2.40 },
    { date: "Apr 17", cost: 1.84 },
  ],
};

export const mockSettings = {
  anthropicApiKey: "sk-ant-api03-••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••",
  fastModel: "claude-haiku-4-5-20251001",
  reasoningModel: "claude-sonnet-4-6",
  outlookEmail: "elio@mcsaccountants.com.au",
  xpmApiKey: "",
  xeroClientId: "",
  xeroClientSecret: "",
  fuseSignApiKey: "fs-••••••••••••••••••••••••",
  teamsWebhook: "https://mcsaccountants.webhook.office.com/webhookb2/••••••••••••••••••",
  confidenceThreshold: 0.75,
  heartbeatInterval: 300,
  autoUpdate: false,
  draftMode: false,
};

export const mockKpis = [
  { name: "WIP Ageing", value: 18, threshold: 14, unit: "days avg", status: "warning", trend: "+2 days" },
  { name: "Debtor Days", value: 28, threshold: 30, unit: "days avg", status: "ok", trend: "-3 days" },
  { name: "Unsigned Docs", value: 3, threshold: 5, unit: "envelopes", status: "ok", trend: "same" },
  { name: "Inbox Backlog", value: 8, threshold: 20, unit: "unread", status: "ok", trend: "-4 emails" },
  { name: "Plugin Failures", value: 1, threshold: 3, unit: "today", status: "ok", trend: "same" },
  { name: "AI Cost Today", value: 1.84, threshold: 5.00, unit: "AUD", status: "ok", trend: "+$0.20" },
];

export const mockSystemStatus = {
  heartbeat: "Active",
  heartbeatTick: 2847,
  fastModel: "claude-haiku-4-5",
  reasoningModel: "claude-sonnet-4-6",
  memoryRecords: 1247,
  costToday: "$1.84",
  uptime: "6h 42m",
  version: "2.4.1",
  updateAvailable: false,
};

export const mockRules = [
  { id: 1, name: "ATO Correspondence", pattern: "from:ato.gov.au", action: "label:ATO", enabled: true, priority: 1 },
  { id: 2, name: "BAS Reminders", pattern: "subject:BAS", action: "plugin:bas_reminder", enabled: true, priority: 2 },
  { id: 3, name: "New Client Enquiry", pattern: "subject:new client OR subject:enquiry", action: "plugin:engagement_letter", enabled: true, priority: 3 },
  { id: 4, name: "FuseSign Notifications", pattern: "from:fusesign.com", action: "plugin:fusesign_monitor", enabled: true, priority: 4 },
];

export const mockStaff = [
  { id: 1, name: "Elio Scarton", email: "elio@mcs.com.au", role: "Principal", notify_approvals: true, notify_briefing: true, notify_alerts: true },
  { id: 2, name: "Sarah Chen", email: "sarah@mcs.com.au", role: "Senior Accountant", notify_approvals: true, notify_briefing: false, notify_alerts: true },
  { id: 3, name: "Marcus Webb", email: "marcus@mcs.com.au", role: "Accountant", notify_approvals: false, notify_briefing: false, notify_alerts: false },
];

export const mockLinks = [
  { id: 1, label: "ATO Portal", url: "https://my.gov.au", category: "Government" },
  { id: 2, label: "XPM Dashboard", url: "https://practice.xero.com", category: "Practice" },
  { id: 3, label: "FuseSign", url: "https://app.fusesign.com", category: "Documents" },
  { id: 4, label: "ASIC Connect", url: "https://connectonline.asic.gov.au", category: "Government" },
];
