// Design: Refined Dark Professional — Dashboard page
// Shows KPI cards, running plugins, recent activity, and system health
// All data fetched from real /api/* endpoints — NO mock data

import {
  Activity,
  AlertTriangle,
  Brain,
  CheckCircle2,
  Clock,
  Cpu,
  DollarSign,
  Play,
  Sun,
  TrendingUp,
  X,
  Zap,
} from "lucide-react";
import { useState, useEffect } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";

const API = "http://127.0.0.1:7842";

function useDashboardData() {
  const [plugins, setPlugins] = useState<any[]>([]);
  const [activity, setActivity] = useState<any[]>([]);
  const [kpis, setKpis] = useState<any[]>([]);
  const [usage, setUsage] = useState<any>(null);
  const [system, setSystem] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAll = async () => {
      try {
        const [pRes, aRes, kRes, uRes, sRes] = await Promise.all([
          fetch(`${API}/api/plugins`),
          fetch(`${API}/api/activity`),
          fetch(`${API}/api/kpi`),
          fetch(`${API}/api/usage`),
          fetch(`${API}/api/system/status`),
        ]);
        if (pRes.ok) setPlugins(await pRes.json());
        if (aRes.ok) setActivity(await aRes.json());
        if (kRes.ok) setKpis(await kRes.json());
        if (uRes.ok) setUsage(await uRes.json());
        if (sRes.ok) setSystem(await sRes.json());
      } catch (_) {
        // backend not yet ready — keep empty state
      } finally {
        setLoading(false);
      }
    };
    fetchAll();
    const interval = setInterval(fetchAll, 30000); // refresh every 30s
    return () => clearInterval(interval);
  }, []);

  return { plugins, activity, kpis, usage, system, loading };
}

function MorningBriefingModal({ onClose }: { onClose: () => void }) {
  const today = new Date().toLocaleDateString("en-AU", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "rgba(0,0,0,0.45)", backdropFilter: "blur(4px)" }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-border"
          style={{ background: "oklch(0.97 0.01 250)" }}>
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg flex items-center justify-center"
              style={{ background: "oklch(0.92 0.06 250)" }}>
              <Sun className="w-5 h-5" style={{ color: "oklch(0.45 0.2 85)" }} />
            </div>
            <div>
              <div className="text-sm font-semibold text-foreground">Morning Briefing Preview</div>
              <div className="text-xs text-muted-foreground">{today} · Sent via Microsoft Teams at 8:00am</div>
            </div>
          </div>
          <button onClick={onClose}
            className="w-7 h-7 rounded-md flex items-center justify-center text-muted-foreground hover:bg-slate-100 hover:text-foreground transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-5 space-y-4" style={{ background: "oklch(0.985 0 0)" }}>
          <div className="rounded-lg border border-border overflow-hidden shadow-sm">
            <div className="px-4 py-3 flex items-center gap-3"
              style={{ background: "oklch(0.25 0.04 250)", color: "white" }}>
              <span className="text-lg">☀️</span>
              <div>
                <div className="text-sm font-semibold">Good morning, MC &amp; S team</div>
                <div className="text-xs opacity-75">{today} · Prepared by CoWorker AI</div>
              </div>
            </div>
            <div className="px-4 py-4 text-sm text-muted-foreground">
              The morning briefing is generated automatically each weekday at 8:00am and sent to the MC &amp; S Teams channel. Configure it in <strong>Plugins → Morning Briefing</strong>.
            </div>
            <div className="px-4 py-3 border-t border-border" style={{ background: "oklch(0.97 0.005 250)" }}>
              <p className="text-xs text-muted-foreground">
                Generated by <strong>MCS CoWorker</strong> · Morning Briefing Plugin
              </p>
            </div>
          </div>
        </div>
        <div className="px-5 py-3 border-t border-border flex items-center justify-between bg-white">
          <span className="text-xs text-muted-foreground">Configure in Plugins → Morning Briefing</span>
          <button onClick={onClose}
            className="px-4 py-2 text-xs font-medium rounded-lg transition-colors"
            style={{ background: "oklch(0.45 0.2 250)", color: "white" }}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Dashboard ─────────────────────────────────────────────────────────────────
export default function Dashboard() {
  const [showBriefing, setShowBriefing] = useState(false);
  const { plugins, activity, kpis, usage, system, loading } = useDashboardData();

  const today = new Date().toLocaleDateString("en-AU", { weekday: "long", day: "numeric", month: "long", year: "numeric" });

  const enabledPlugins = plugins.filter((p: any) => p.enabled !== false);
  const runningPlugins = plugins.filter((p: any) => p.status === "running");
  const totalRunsToday = enabledPlugins.reduce((sum: number, p: any) => sum + (p.runsToday ?? p.runs_today ?? 0), 0);
  const avgSuccessRate = enabledPlugins.length > 0
    ? Math.round(enabledPlugins.reduce((sum: number, p: any) => sum + (p.successRate ?? p.success_rate ?? 100), 0) / enabledPlugins.length)
    : 0;

  const todayCost = usage?.todayCost ?? usage?.today_cost ?? 0;
  const monthlyBudget = usage?.monthlyBudget ?? usage?.monthly_budget ?? 100;
  const memoryRecords = system?.memoryRecords ?? system?.memory_records ?? 0;
  const uptime = system?.uptime ?? "—";
  const byDay = usage?.byDay ?? usage?.by_day ?? [];

  const allOk = system?.status === "ok" || (!loading && plugins.length > 0);

  return (
    <div className="p-6 space-y-6">
      {showBriefing && <MorningBriefingModal onClose={() => setShowBriefing(false)} />}

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-foreground">Dashboard</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            {today}{uptime !== "—" ? ` · Uptime ${uptime}` : ""}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => setShowBriefing(true)}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium border border-border bg-white hover:bg-slate-50 transition-colors shadow-sm"
          >
            <Sun className="w-3.5 h-3.5" style={{ color: "oklch(0.55 0.15 85)" }} />
            Preview Morning Briefing
          </button>
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium"
            style={{ background: "oklch(0.95 0.05 145)", color: "oklch(0.35 0.12 145)" }}>
            <span className="status-dot running" />
            {loading ? "Loading..." : allOk ? "All systems operational" : "Checking systems..."}
          </div>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="stat-card">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Runs Today</span>
            <div className="w-7 h-7 rounded-md flex items-center justify-center" style={{ background: "oklch(0.94 0.05 250)" }}>
              <Play className="w-3.5 h-3.5" style={{ color: "oklch(0.5 0.2 250)" }} />
            </div>
          </div>
          <div className="text-2xl font-bold text-foreground">{loading ? "—" : totalRunsToday}</div>
          <div className="text-xs text-muted-foreground mt-1">across {enabledPlugins.length} active plugins</div>
        </div>

        <div className="stat-card">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Success Rate</span>
            <div className="w-7 h-7 rounded-md flex items-center justify-center" style={{ background: "oklch(0.94 0.08 145)" }}>
              <CheckCircle2 className="w-3.5 h-3.5" style={{ color: "oklch(0.5 0.15 145)" }} />
            </div>
          </div>
          <div className="text-2xl font-bold text-foreground">{loading ? "—" : `${avgSuccessRate}%`}</div>
          <div className="text-xs text-muted-foreground mt-1">last 7 days average</div>
        </div>

        <div className="stat-card">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">AI Cost Today</span>
            <div className="w-7 h-7 rounded-md flex items-center justify-center" style={{ background: "oklch(0.94 0.05 85)" }}>
              <DollarSign className="w-3.5 h-3.5" style={{ color: "oklch(0.55 0.15 85)" }} />
            </div>
          </div>
          <div className="text-2xl font-bold text-foreground">{loading ? "—" : `$${Number(todayCost).toFixed(2)}`}</div>
          <div className="text-xs text-muted-foreground mt-1">of ${monthlyBudget} monthly budget</div>
        </div>

        <div className="stat-card">
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Memory Records</span>
            <div className="w-7 h-7 rounded-md flex items-center justify-center" style={{ background: "oklch(0.94 0.05 300)" }}>
              <Brain className="w-3.5 h-3.5" style={{ color: "oklch(0.5 0.15 300)" }} />
            </div>
          </div>
          <div className="text-2xl font-bold text-foreground">{loading ? "—" : Number(memoryRecords).toLocaleString()}</div>
          <div className="text-xs text-muted-foreground mt-1">client interactions stored</div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* KPI Monitor */}
        <div className="lg:col-span-1 bg-white rounded-lg border border-border shadow-sm">
          <div className="px-4 py-3 border-b border-border flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-muted-foreground" />
            <span className="text-sm font-semibold text-foreground">KPI Monitor</span>
          </div>
          <div className="p-4 space-y-3">
            {loading ? (
              <div className="text-xs text-muted-foreground py-4 text-center">Loading KPIs...</div>
            ) : kpis.length === 0 ? (
              <div className="text-xs text-muted-foreground py-4 text-center">No KPI data available</div>
            ) : kpis.map((kpi: any) => (
              <div key={kpi.name} className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  {kpi.status === "warning" ? (
                    <AlertTriangle className="w-3.5 h-3.5 text-amber-500" />
                  ) : (
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                  )}
                  <span className="text-sm text-foreground">{kpi.name}</span>
                </div>
                <div className="text-right">
                  <span className={`text-sm font-mono font-semibold ${kpi.status === "warning" ? "text-amber-600" : "text-foreground"}`}>
                    {kpi.unit === "AUD" ? `$${kpi.value}` : kpi.value}
                    <span className="text-xs font-normal text-muted-foreground ml-1">{kpi.unit}</span>
                  </span>
                  <div className="text-xs text-muted-foreground">{kpi.trend}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Cost chart */}
        <div className="lg:col-span-2 bg-white rounded-lg border border-border shadow-sm">
          <div className="px-4 py-3 border-b border-border flex items-center gap-2">
            <Zap className="w-4 h-4 text-muted-foreground" />
            <span className="text-sm font-semibold text-foreground">AI Cost — Last 7 Days</span>
          </div>
          <div className="p-4">
            {byDay.length === 0 ? (
              <div className="h-[180px] flex items-center justify-center text-xs text-muted-foreground">
                {loading ? "Loading chart data..." : "No cost data available yet"}
              </div>
            ) : (
              <ResponsiveContainer width="100%" height={180}>
                <BarChart data={byDay} barSize={28}>
                  <XAxis dataKey="date" tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} tickFormatter={(v) => `$${v}`} />
                  <Tooltip
                    formatter={(v: number) => [`$${v.toFixed(2)}`, "Cost"]}
                    contentStyle={{ fontSize: 12, borderRadius: 6, border: "1px solid #e2e8f0" }}
                  />
                  <Bar dataKey="cost" fill="oklch(0.5 0.2 250)" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Active plugins */}
        <div className="bg-white rounded-lg border border-border shadow-sm">
          <div className="px-4 py-3 border-b border-border flex items-center gap-2">
            <Cpu className="w-4 h-4 text-muted-foreground" />
            <span className="text-sm font-semibold text-foreground">Active Plugins</span>
            <span className="ml-auto badge info">{runningPlugins.length} running</span>
          </div>
          <div className="divide-y divide-border">
            {loading ? (
              <div className="px-4 py-6 text-xs text-muted-foreground text-center">Loading plugins...</div>
            ) : enabledPlugins.length === 0 ? (
              <div className="px-4 py-6 text-xs text-muted-foreground text-center">No active plugins</div>
            ) : enabledPlugins.slice(0, 6).map((plugin: any) => (
              <div key={plugin.id} className="flex items-center gap-3 px-4 py-3">
                <span className={`status-dot ${plugin.status ?? "idle"}`} />
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium text-foreground truncate">{plugin.name}</div>
                  <div className="text-xs text-muted-foreground">
                    {plugin.lastRun ?? plugin.last_run ?? "Never"} · {plugin.runsToday ?? plugin.runs_today ?? 0} runs today
                  </div>
                </div>
                <span className={`badge ${(plugin.model ?? "").includes("sonnet") ? "info" : "neutral"}`}>
                  {plugin.model ?? "—"}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Recent activity */}
        <div className="bg-white rounded-lg border border-border shadow-sm">
          <div className="px-4 py-3 border-b border-border flex items-center gap-2">
            <Activity className="w-4 h-4 text-muted-foreground" />
            <span className="text-sm font-semibold text-foreground">Recent Activity</span>
          </div>
          <div className="divide-y divide-border">
            {loading ? (
              <div className="px-4 py-6 text-xs text-muted-foreground text-center">Loading activity...</div>
            ) : activity.length === 0 ? (
              <div className="px-4 py-6 text-xs text-muted-foreground text-center">No activity yet</div>
            ) : activity.slice(0, 6).map((log: any) => (
              <div key={log.id} className="flex items-start gap-3 px-4 py-3">
                <div className="flex-shrink-0 mt-0.5">
                  {log.status === "success" && <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />}
                  {log.status === "error" && <AlertTriangle className="w-3.5 h-3.5 text-rose-500" />}
                  {(log.status === "warning" || !log.status) && <Clock className="w-3.5 h-3.5 text-amber-500" />}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-xs font-medium text-foreground">{log.plugin ?? log.source ?? "System"}</div>
                  <div className="text-xs text-muted-foreground truncate">{log.action ?? log.payload ?? log.message ?? ""}</div>
                </div>
                <span className="text-xs text-muted-foreground flex-shrink-0">{log.time ?? log.timestamp ?? ""}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
