"""One-off audit script. Run manually once. Output is committed alongside this script.

Lists every immediate child folder under SHAREPOINT_CLIENT_BASE (Server/Clients/),
groups them by their normalised key (the form `normalise_client_name` would produce),
and reports collision groups so we can see which client folders have drifted into
duplicates.

Usage (run from the repo root, on a machine that has the MSAL token cache):

    python scripts/audit_sharepoint_duplicates.py

Reuses GraphClient.get_sharepoint_site_id and get_sharepoint_drive_id — no new
auth path. Writes the report to docs/recon/sharepoint_duplicates_audit.md.

DO NOT integrate this into the running app. It is not a plugin and has no tests.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

# Allow running from the repo root: import siblings of this script's parent.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from graph_client import (  # noqa: E402
    GraphClient,
    GRAPH_BASE,
    SHAREPOINT_CLIENT_BASE,
)
from client_utils import normalise_client_name  # noqa: E402


REPORT_PATH = REPO_ROOT / "docs" / "recon" / "sharepoint_duplicates_audit.md"
TOP_N = 20


def list_client_folders(graph: GraphClient, drive_id: str) -> list[dict]:
    """Return every immediate child of SHAREPOINT_CLIENT_BASE that is a folder.

    Pages through Graph's @odata.nextLink until exhausted so we aren't capped at
    the default 200. Each entry: {name, id, child_count}.
    """
    folders: list[dict] = []
    url = (
        f"{GRAPH_BASE}/drives/{drive_id}/root:/{SHAREPOINT_CLIENT_BASE}"
        f":/children?$top=200&$select=id,name,folder"
    )
    while url:
        result = graph._make_request("GET", url)
        if not result or "value" not in result:
            break
        for item in result["value"]:
            folder_meta = item.get("folder")
            if not folder_meta:
                continue  # skip files at the root, only count folders
            folders.append({
                "id": item.get("id", ""),
                "name": item.get("name", ""),
                "child_count": folder_meta.get("childCount", 0),
            })
        url = result.get("@odata.nextLink")
    return folders


def group_by_normalised(folders: list[dict]) -> dict[str, list[dict]]:
    """Group folders by the key normalise_client_name produces from their name."""
    groups: dict[str, list[dict]] = defaultdict(list)
    for folder in folders:
        try:
            key = normalise_client_name(folder["name"])
        except Exception:
            key = folder["name"]  # never lose a row to a normalisation error
        groups[key].append(folder)
    return groups


def render_report(folders: list[dict],
                  groups: dict[str, list[dict]]) -> str:
    collision_groups = {k: v for k, v in groups.items() if len(v) > 1}
    sorted_collisions = sorted(
        collision_groups.items(),
        key=lambda kv: (-len(kv[1]), kv[0].lower()),
    )

    lines: list[str] = []
    lines.append("# SharePoint client folder duplication audit")
    lines.append("")
    lines.append(f"_Generated: {datetime.utcnow().isoformat()}Z_")
    lines.append("")
    lines.append(f"- Root scanned: `{SHAREPOINT_CLIENT_BASE}/`")
    lines.append(f"- Total folders: {len(folders)}")
    lines.append(f"- Normalisation-collision groups (>1 folder): "
                 f"{len(collision_groups)}")
    lines.append("")
    lines.append(f"## Top {TOP_N} collision groups")
    lines.append("")

    if not sorted_collisions:
        lines.append("_No collisions found._")
    else:
        for key, members in sorted_collisions[:TOP_N]:
            lines.append(f"### `{key}` — {len(members)} folders")
            lines.append("")
            lines.append("| Verbatim name | childCount |")
            lines.append("|---------------|-----------:|")
            for member in members:
                verbatim = member["name"].replace("|", "\\|")
                lines.append(f"| `{verbatim}` | {member['child_count']} |")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by `scripts/audit_sharepoint_duplicates.py`._")
    return "\n".join(lines) + "\n"


def main() -> int:
    graph = GraphClient()
    site_id = graph.get_sharepoint_site_id()
    if not site_id:
        print("ERROR: could not resolve SharePoint site id "
              "(check Microsoft 365 sign-in).", file=sys.stderr)
        return 1
    drive_id = graph.get_sharepoint_drive_id(site_id)
    if not drive_id:
        print("ERROR: could not resolve SharePoint drive id.", file=sys.stderr)
        return 1

    folders = list_client_folders(graph, drive_id)
    print(f"Scanned {len(folders)} folders under {SHAREPOINT_CLIENT_BASE}/")

    groups = group_by_normalised(folders)
    report = render_report(folders, groups)

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
